### ISSUE TITLE
Particle Pi API on Mobile Data Connection

### ISSUE THREAD

**Issue by ashtonsmith** [spark/particle-agent#6]
Hello.
Ive got a raspberry pi running the particle agent, and it works really fantastic, Thanks guys! 
Im just having one issue. the device wont recieve commands from the api when its connected via 3G.. we're trying to build a system that will rely on 3G connectivity, as it will be away from wifi/ethernet. im not sure if its something that the isp is blocking or what we can do.
I wondered if it is perhaps because (being a mobile connection) it doesnt have a public IP address - most if not all mobile networks are like that, and presumably, this works on the electron, so im not sure what the go is.
Im testing with a Raspberry pi3, a huawei usb 3g modem, and Vodafone NZ sim card (in NZ) the device can browse the web fine, and send https post commands to my api, it just cant recieve commands from the particle api.
As a side note, i have also tried piping it down an always on vpn connection, but this didnt work for me either.

i posted this to Particle support, and they suggested posting here.
Any Pointers?

Thanks

**Comment by kennethlimcp** [comment]
Does the raspberry pi connect to the ☁️ and listed as online in the console/CLI?

**Comment by ashtonsmith** [comment]
hi, yes it does, and the console shows the device came online notification, but nothing after that, sending commands results in the device promptly showing as offline. Thanks

**Comment by kennethlimcp** [comment]
Can you check the logs of the raspberry pi for any hints on of the issue?

Also, can you try running tinker and see if you can control the D7 led?

**Comment by ashtonsmith** [comment]
Hello.

Sorry, my bad, i just wiped the pi and re-configured it, and it seems to be working fine... it must have been something else interfering with it.

Sorry to hassle, keep up the good work!

Thanks
